name: Push-to-Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Push to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "165.22.82.104"
          REMOTE_USER: "root"
          TARGET: "/var/www/devopstest"
